# Generated by Django 3.0 on 2022-03-20 19:44
from django.db import migrations
from django.apps import apps as global_apps


def duplicate_table(apps, schema_editor):

    try:
        Profile = apps.get_model('oc_lettings_site', 'Profile')
    except LookupError:
        return
    NewProfile = apps.get_model('profiles', 'Profile')
    profiles_list = list()
    for profile in Profile.objects.all():
        new = NewProfile(user=profile.user,
                         favorite_city=profile.favorite_city)
        profiles_list.append(new)
    NewProfile.objects.bulk_create(profiles_list)


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial')
    ]

    operations = [
        migrations.RunPython(duplicate_table, migrations.RunPython.noop),
    ]

    if global_apps.is_installed("oc_lettings_site"):
        dependencies.append(("oc_lettings_site", "0001_initial"))