version: 2.1

orbs: 
  heroku: circleci/heroku@1.2.6

jobs:
  build_test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: install packages
          command: |
            pip install --user --no-cache-dir -r requirements.txt
          when: always
      - run:
          name: Run Linting
          command: flake8 
      - run:
          name: Run Pytest
          command: pytest

  heroku-deploy:
    machine: true
    steps:
      - checkout
      - heroku/install
      - run: |
          heroku config:set ENV=production -a $HEROKU_APP_NAME
          heroku config:set SECRET_KEY=$SECRET_KEY -a $HEROKU_APP_NAME
      - heroku/deploy-via-git


workflows:
  test_build:
    jobs:
      - build_test
      - heroku-deploy:
          requires:
            - build_test

